# Generated by Django 4.1.7 on 2023-03-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                default="Developer", max_length=63, unique=True
            ),
        ),
    ]
