# Generated by Django 4.1.7 on 2023-03-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                ("description", models.TextField()),
                ("deadline", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "In development"),
                            (2, "In support"),
                            (3, "Deployed"),
                            (4, "Closed"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(related_name="projects", to="board.task"),
                ),
            ],
        ),
    ]
