# Generated by Django 4.1.7 on 2023-03-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tasks",
            field=models.ManyToManyField(
                null=True, related_name="projects", to="board.task"
            ),
        ),
    ]
