# Generated by Django 4.1.7 on 2023-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_alter_project_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateTimeField(),
        ),
    ]
